version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: chat
      POSTGRES_PASSWORD: chat123
      POSTGRES_DB: play-chat
    ports:
      - "5432:5432"
